name: Unity CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: List Directory Contents
        run: |
          dir "D:\Hub\2022.3.7f1\Editor"
        shell: powershell

      - name: Set up Unity License
        run: |
          echo "${{ secrets.UNITY_LICENSE }}" > Unity_v2022.x.ulf
          mkdir "D:\Hub\2022.3.7f1"
          move Unity_v2022.x.ulf "D:\Hub\2022.3.7f1\Unity_v2022.x.ulf"
        shell: powershell
        
      - name: Cache Unity packages
        uses: actions/cache@v2
        with:
          path: Library
          key: ${{ runner.os }}-unity-${{ hashFiles('**/PackagesLock.json') }}
          
      - name: Build project
        run: |
          Start-Process -FilePath "D:\Hub\2022.3.7f1\Editor\Unity.exe" `
                        -ArgumentList '-quit', '-batchmode', '-nographics', '-projectPath', '.', '-buildTarget', 'StandaloneWindows64', '-buildPath', 'build\StandaloneWindows64' `
                        -NoNewWindow -Wait
        continue-on-error: true
        
      - name: Set build artifact path
        run: echo "BUILD_PATH=build\StandaloneWindows64" >> $GITHUB_ENV
        
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.BUILD_PATH }}
